name: "Main action file to create tag"

description: "composite actions"

inputs:
  GITHUB_TOKEN:
    description: "Token used to access repo"
    required: false
  PR_NUMBER:
    description: PR number
    required: false

runs:
  using: "composite"
  steps:
    - name: making pr as draft 
      run: |
        echo $PR_NUMBER
        if [[ "$LABEL" == "true" ]]; then
          echo This PR has a Label named DO_NOT_MERGE. Converting it into DRAFT PR
          bash ./scripts/draft.sh $PR_NUMBER
        else
          echo This PR doesn't has a Label named DO_NOT_MERGE.
        fi
      shell: bash
