name: "Main action file to create tag"

description: "composite actions"

inputs:
  GITHUB_TOKEN:
    description: "Token used to access repo"
    required: false
  PR_NUMBER:
    description: PR number
    required: false

runs:
  using: "composite"
  steps:
    - name: making pr as draft 
      run: |
        echo $PR_NUMBER
        bash ./scripts/draft.sh $PR_NUMBER
      shell: bash
