name: 'PR having DO_NOT_MERGE Label should Be converted as DRAFT PR'

on:
  pull_request:
    types: [opened, edited, reopened, labeled]

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  make_pr_draft:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: make pr draft
        uses: officialmanishkr98/github-actions/actions/pr_draft@main


# README -> secrets.GITHUB_TOKEN doesn't work as it doesn't has necessary permissions. So create a PAT 
#           with necessary permissions and use it instead