name: Make PR Draft

on:
  push:
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - master

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}
  PR_NUMBER: 4

jobs:
  make_pr_draft:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
        
      # - name: make pr draft
      #   uses: officialmanishkr98/github-actions/actions/pr_draft@main
      - name: Run draft.sh script
        run: |
          gh pr view 4
          
          id=$(gh pr view $1 --json id -q '.id')

          MUTATION='
            mutation($id: ID!) {
              convertPullRequestToDraft(input: { pullRequestId: $id }) {
                pullRequest {
                  id
                  number
                  isDraft
                }
              }
            }'
          
          gh api graphql -F id="${id}" -f query="${MUTATION}" >/dev/null

        shell: bash

        