name: Make PR Draft when it has a label named DO_NOT_MERGE

on:
  push:
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - master

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}
  PR_NUMBER: 4

jobs:
  make_pr_draft:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: make pr draft
        uses: officialmanishkr98/github-actions/actions/pr_draft@main
 