name: 'PR having DO_NOT_MERGE Label should Be converted as DRAFT PR'

on:
  push:
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - master

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}
  PR_NUMBER: 4

jobs:
  make_pr_draft:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: make pr draft
        uses: officialmanishkr98/github-actions/actions/pr_draft@main


# README -> secrets.GITHUB_TOKEN doesn't work as it doesn't has necessary permissions. So create a PAT 
#           with necessary permissions and use it instead