name: 'PR Description and Target Checker'
on:
  pull_request:
    types: [opened, edited, reopened]
      
permissions: write-all    
      
env:
  JOB: PR_CHECKER
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_NAME: ${{ github.repository }}
  PR_NUMBER: ${{ github.event.pull_request.number }}
  WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
 
jobs:
  Check-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check PR Description and Target
        uses: ./   
