name: Stale Pull Requests
on:
  push:
  # schedule:
  #   - cron: '0 09 * * *' # scheduler runs every day at 9:00am UTC

permissions: write-all

env:
  JOB: PR_MONITOR
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  REPO_NAME: ${{ github.repository }}
  WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}

jobs:
  Stale-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Stale PR
        uses: ./    